name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from your GitHub repo
      - uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      # Step 4: Run tests
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

      # Step 5: Lint & format check
      - name: Lint
        run: |
          pip install black flake8
          black --check .
          flake8
